# Dockerfile for local development
# Setting official golang image tag 1.16.5 as baseimage
FROM golang:1.16.5
VOLUME /payment
WORKDIR /payment
RUN go get github.com/githubnemo/CompileDaemon
EXPOSE 80
ENTRYPOINT ["sh","scripts/docker-entrypoint.sh"]
